# fly.toml app configuration file generated for letterboxd-app on 2023-09-15T11:06:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "letterboxd-app"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"
  USE_DATABASE_URL = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
